name: "Polkadot Runtime Releaser Try Runtime Action"
description: >
  Provides a way to run try-runtime for the polkadot-sdk-based runtime in GitHub Action with the Polkadot Runtime Releaser (PPR) CLI.
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  runtime:
    description: >
      Use `prr build --help` to get more information.

      Or check the https://github.com/hack-ink/polkadot-runtime-releaser/blob/main/README.md#usage
    required: true
  features:
    description: >
      Use `prr build --help` to get more information.

      Or check the https://github.com/hack-ink/polkadot-runtime-releaser/blob/main/README.md#usage
    required: false
  toolchain-ver:
    description: >
      Use `prr build --help` to get more information.

      Or check the https://github.com/hack-ink/polkadot-runtime-releaser/blob/main/README.md#usage
    required: false
  try-runtime-ver:
    description: >
      Try Runtime CLI version to use. Default is 0.8.0.
    required: false
    default: 0.8.0
  blocktime:
    description: >
      Block time of the runtime.
    required: false
    default: "6000"
  disable-spec-version-check:
    description: >
      Whether to skip enforcing that the new runtime `spec_version` is greater or equal to the existing `spec_version`.
    required: false
  disable-idempotency-checks:
    description: >
      Whether to disable migration idempotency checks.
    required: false
  uri:
    description: >
      Node URI to use.
    required: true

runs:
  using: "composite"
  steps:
    - name: React comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ github.event.comment.id }}
        reactions: rocket,eyes
    - name: Setup try runtime CLI
      shell: bash
      run: curl
        -L https://github.com/paritytech/try-runtime-cli/releases/download/v${{ inputs.try-runtime-ver }}/try-runtime-x86_64-unknown-linux-musl
        -o try-runtime &&
        chmod +x try-runtime &&
        mv try-runtime /usr/local/bin/try-runtime
    - name: Build runtime
      uses: hack-ink/polkadot-runtime-releaser/action/build@v0.2.0
      with:
        runtime: ${{ inputs.runtime }}
        features: ${{ inputs.features }}
        toolchain-ver: ${{ inputs.toolchain-ver }}
        output-dir: .
    - name: Try runtime
      id: try_runtime
      shell: bash
      # Remove `grep -vE '[⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏]'`.
      # https://github.com/paritytech/polkadot-sdk/issues/7010
      run: |
        CMD="try-runtime \
          --runtime $(ls *_runtime-*.compact.compressed.wasm) \
          on-runtime-upgrade \
          --blocktime ${{ inputs.blocktime }}"

        if [ "${{ inputs.disable-spec-version-check }}" = "true" ]; then
          CMD="$CMD --disable-spec-version-check"
        fi
        if [ "${{ inputs.disable-idempotency-checks }}" = "true" ]; then
          CMD="$CMD --disable-idempotency-checks"
        fi

        CMD="$CMD live -u ${{ inputs.uri }}"
        OUTPUT=$(eval "$CMD" 2>&1 | grep -vE '[⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏]' || true)

        echo "result<<EOF" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Comment result
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          <details>
          <summary>try-runtime result of `${{ inputs.runtime }}`</summary>

          ```
          ${{ steps.try_runtime.outputs.result }}
          ```
          </details>
