name: "Polkadot Runtime Releaser Try Runtime Action"
description: "Polkadot Runtime Releaser Try Runtime Action."
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  runtime:
    description: "Target runtime to build."
    required: true
  features:
    description: "Features to enable for the runtime."
    required: false
  toolchain-ver:
    description: "Rust toolchain version to use."
    required: false
  try-runtime-version:
    description: "Try Runtime CLI version to use."
    required: false
    default: "0.8.0"
  uri:
    description: "Node URI to use."
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup try runtime CLI
      shell: bash
      run: curl
        -L https://github.com/paritytech/try-runtime-cli/releases/download/v${{ inputs.try-runtime-version }}/try-runtime-x86_64-unknown-linux-musl
        -o try-runtime &&
        chmod +x try-runtime &&
        mv try-runtime /usr/local/bin/try-runtime
    - name: Build runtime
      uses: hack-ink/polkadot-runtime-releaser/action/build@0.1.8
      with:
        runtime: ${{ inputs.runtime }}
        features: ${{ inputs.features }}
        toolchain-ver: ${{ inputs.toolchain-ver }}
    - name: Try runtime
      id: try_runtime
      shell: bash
      run: |
        echo "output<<EOF" >> $GITHUB_OUTPUT
        try-runtime \
          --runtime $(find ./polkadot-runtime-releaser-output \
          -name "*.compact.compressed.wasm") \
          on-runtime-upgrade \
          live \
          -u ${{ inputs.uri }} \
          2>&1 >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Comment result
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          <details>
          <summary>Try Runtime Output for ${{ inputs.runtime }}</summary>

          ```
          ${{ steps.try_runtime.outputs.output }}
          ```
          </details>
