name: "Polkadot Runtime Releaser Inspect Action"
description: >
  Provides a way to inspect polkadot-sdk-based runtime in GitHub Action with the Polkadot Runtime Releaser (PRR) CLI.
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  runtime:
    description: >
      Use `prr inspect --help` to get more information.

      Or check the https://github.com/hack-ink/polkadot-runtime-releaser/blob/main/README.md#usage
    required: true
  no-check-version:
    description: >
      Use `prr inspect --help` to get more information.

      Or check the https://github.com/hack-ink/polkadot-runtime-releaser/blob/main/README.md#usage`ParachainSystem::authorized_upgrade` call."
    required: false
  beautify:
    description: >
      Use `prr inspect --help` to get more information.

      Or check the https://github.com/hack-ink/polkadot-runtime-releaser/blob/main/README.md#usage
    required: false
  verbose:
    description: >
      Use `prr inspect --help` to get more information.

      Or check the https://github.com/hack-ink/polkadot-runtime-releaser/blob/main/README.md#usage
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Polkadot Runtime Releaser
      shell: bash
      run: curl
        -L https://github.com/hack-ink/polkadot-runtime-releaser/releases/download/v0.2.0/prr-x86_64-unknown-linux-gnu.tar.gz |
        tar xz &&
        chmod u+x prr &&
        mv prr /usr/local/bin/prr
    - name: Inspect runtime
      id: inspect
      shell: bash
      run: |
        CMD="prr inspect ${{ inputs.runtime }}"
        if [ ! -z "${{ inputs.no-check-version }}" ]; then
          CMD="$CMD --no-check-version"
        fi
        if [ ! -z "${{ inputs.beautify }}" ]; then
          CMD="$CMD -b"
        fi
        if [ ! -z "${{ inputs.verbose }}" ]; then
          CMD="$CMD -v"
        fi

        RESULT=$(${CMD})
        echo "result=${RESULT}" >> "$GITHUB_OUTPUT"

outputs:
  result:
    description: "Inspect result."
    value: ${{ steps.inspect.outputs.result }}
