name: "Polkadot Runtime Releaser Override Action"
description: >
  Provides a way to build and commit the polkadot-sdk-based override runtime in GitHub Action with the Polkadot Runtime Releaser (PPR) CLI.
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  repository:
    description: >
      Repository to fetch the runtime code from.
    required: true
  ref:
    description: >
      Branch, tag, or commit of the runtime repository to fetch.
    required: true
  runtime:
    description: >
      Use `prr build --help` to get more information.

      Or check the https://github.com/hack-ink/polkadot-runtime-releaser/blob/main/README.md#usage
    required: true
  features:
    description: >
      Use `prr build --help` to get more information.

      Or check the https://github.com/hack-ink/polkadot-runtime-releaser/blob/main/README.md#usage
    required: true
  toolchain-ver:
    description: >
      Use `prr build --help` to get more information.

      Or check the https://github.com/hack-ink/polkadot-runtime-releaser/blob/main/README.md#usage
    required: false
  token:
    description: >
      Use a Personal Access Token (PAT) if `GITHUB_TOKEN` does not have enough permissions to commit the overrides.
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Fetch latest code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.runtime }}
        path: override
    - name: Fetch runtime code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: runtime
    - name: Build runtime
      uses: hack-ink/polkadot-runtime-releaser/action/build@v0.2.0
      with:
        runtime: ${{ inputs.runtime }}
        features: ${{ inputs.features }}
        toolchain-ver: ${{ inputs.toolchain-ver }}
        workdir: runtime
        output-dir: override/${{ inputs.features }}
    - name: Commit changes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        cd override
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Override \`${{ inputs.ref }}\`"
        git pull --rebase origin ${{ inputs.runtime }}
        git push
